### ISSUE TITLE
Doesn't handle all versions of windows

### ISSUE THREAD

**Issue by k4n30** [bitsadmin/wesng#1]
> Every Windows OS between Windows XP and Windows 10, including their Windows Server counterparts, is supported

I noticed there are quite a few versions of windows which have been missed, or not handled correctly. I initially noticed it on 2008 R2 which was being reported as 2008 (different build numbers) which reported 2564 vulnerabilities found :O looks like windows 8 (& 8.1) and 2012's are missing too. I didn't have these on hand to test to verify, but a quick look at wes.py doesn't even list these versions

https://en.wikipedia.org/wiki/Comparison_of_Microsoft_Windows_versions#Windows_NT

**Comment by k4n30** [comment]
Extract of systeminfo
`OS Name:                   Microsoft Windows Server 2008 R2 Datacenter 
OS Version:                6.1.7601 Service Pack 1 Build 7601`

Corresponding wes-ng output from this systeminfo output
`Operating System
    - Name: Windows Server 2008 for x64-based Systems
    - Generation: 2008
    - Build: 7601
    - Version: Service Pack 1
    - Architecture: x64-based`

**Comment by bitsadmin** [comment]
Thanks k4n30! I totally overlooked these OS versions in the wes.py script. Just added checks so these are also recognized from the systeminfo output. These OS versions were already included in the collector, so that should work without any issues. Thanks again and let me know in case you run into any other issues.
