### ISSUE TITLE
WESNG not recognizing correctly systeminfo.txt

### ISSUE THREAD

**Issue by kusa53** [bitsadmin/wesng#27]
Windows Exploit Suggester 0.95 ( https://github.com/bitsadmin/wesng/ )
[+] Parsing systeminfo output
[-] Not able to detect OS name based on provided input file

I get this with the below systeminfo.txt

> Nom de l'hôte:                              WIN-JBSO216CKQM
> Nom du système d'exploitation:              Microsoft Windows 7 Entreprise N 
> Version du système:                         6.1.7601 Service Pack 1 version 7601
> Fabricant du système d'exploitation:        Microsoft Corporation
> ...

By replacing "Microsoft Windows 7 Entreprise N"  by "Microsoft Windows 7 Professionnel", it seems to work but not convenient.

**Comment by bitsadmin** [comment]
Thanks for the feedback. I managed to reproduce the issue and it has been fixed in v0.96: [CHANGELOG.md](https://github.com/bitsadmin/wesng/blob/master/CHANGELOG.md).

Make sure to create the systeminfo.txt using PowerShell as cmd.exe stores the file in ascii.

Test file: [7_sp1_x64_enterprise_fr_systeminfo_powershell.txt](https://github.com/bitsadmin/wesng/blob/master/validation/7_sp1_x64_enterprise_fr_systeminfo_powershell.txt)
