### ISSUE TITLE
Microsoft KB integrated into version 1909

### ISSUE THREAD

**Issue by Will-777** [bitsadmin/wesng#44]
Scanning today on my Windows, and I've found lot of vulnerabilities : 
[+] Done. Displaying 123 of the 123 vulnerabilities found.

After a quick check, it was Windows 10, version 1909 and according
this security update includes quality improvements. Key changes include:
https://support.microsoft.com/en-us/help/4551762/windows-10-update-kb4551762

It means that your scanner is not really working with build 1909 ?
Thanks.

**Comment by bitsadmin** [comment]
Thanks Will-777 for your message!

I am not sure whether this is because of the incomplete MSRC feed (see instructions in README) or the fact that the build number of Windows 10 1909 was not yet added to the wes.py script. Anyways, I just added the build number in [this commit](https://github.com/bitsadmin/wesng/commit/d92476f256ed3fa56ee25a8faa1c1308fa9118e5).

**Comment by bitsadmin** [comment]
No response in quite a while and no other bugs related to version 1909 have been submitted, so it seems to be working well now. Closing this bug.
