### ISSUE TITLE
Missing cve - Windows 10

### ISSUE THREAD

**Issue by sebastienfnt1** [bitsadmin/wesng#56]
Hi!

I noticed that the last vulnerabilities (ex: CVE-2021-34527) did not appear in the results.  Same observation with the validation files except for Windows 7 and Windows server 2012.

My system : Windows 10 1809

Thx

**Comment by sebastienfnt1** [comment]
update 

results : 

[+] Missing patches: 18
    - KB4512578: patches 112 vulnerabilities
    - KB5005030: patches 52 vulnerabilities
    - KB4507419: patches 6 vulnerabilities
    - KB4483452: patches 4 vulnerabilities
    - KB4556441: patches 4 vulnerabilities
    - KB4535101: patches 4 vulnerabilities
    - KB4578973: patches 4 vulnerabilities
    - KB4570505: patches 4 vulnerabilities
    - KB4514601: patches 2 vulnerabilities
    - KB4535680: patches 2 vulnerabilities
    - KB4601887: patches 2 vulnerabilities
    - KB4465664: patches 1 vulnerability
    - KB4477029: patches 1 vulnerability
    - KB4487038: patches 1 vulnerability
    - KB4516115: patches 1 vulnerability
    - KB4519337: patches 1 vulnerability
    - KB4558997: patches 1 vulnerability
    - KB4580325: patches 1 vulnerability
[+] KB with the most recent release date
    - ID: KB5005030
    - Release date: 20210812

with windows 10 x64 1809 and hotfix i have 202 vulnerabilities
without hotfix i have 203 vulnerabilites 

on website : https://msrc.microsoft.com/update-guide/ with filters products familly windows and product windows 10 1809 x64 i have more 1500 vulnerabilties

i don't understand why wesng bypass lot of vulnerabilities (exemple : CVE-2021-34460, CVE-2021-34527, CVE-2021-34456, CVE-2021-33774, CVE-2020-17096 etc etc.) because no kb was install.

how to explain ?

best regards

**Comment by bitsadmin** [comment]
Hi sebastienfnt1, thanks for your messages!

> Hi!
> 
> I noticed that the last vulnerabilities (ex: CVE-2021-34527) did not appear in the results. Same observation with the validation files except for Windows 7 and Windows server 2012.
> 
> My system : Windows 10 1809
> 
> Thx

WES-NG collects information from the Microsoft Security Response Center (MSRC) feed. If in that feed the KB doesn't reference a CVE, it also won't show up in the results of WES-NG. The feeds however are regularly updated and also the WES-NG definitions file. For that reason, maybe in the next update of the definitions.zip file, the link between the KB and CVE might be added.

> update
> 
> results :
> 
> [+] Missing patches: 18
> - KB4512578: patches 112 vulnerabilities
> - KB5005030: patches 52 vulnerabilities
> - KB4507419: patches 6 vulnerabilities
> - KB4483452: patches 4 vulnerabilities
> - KB4556441: patches 4 vulnerabilities
> - KB4535101: patches 4 vulnerabilities
> - KB4578973: patches 4 vulnerabilities
> - KB4570505: patches 4 vulnerabilities
> - KB4514601: patches 2 vulnerabilities
> - KB4535680: patches 2 vulnerabilities
> - KB4601887: patches 2 vulnerabilities
> - KB4465664: patches 1 vulnerability
> - KB4477029: patches 1 vulnerability
> - KB4487038: patches 1 vulnerability
> - KB4516115: patches 1 vulnerability
> - KB4519337: patches 1 vulnerability
> - KB4558997: patches 1 vulnerability
> - KB4580325: patches 1 vulnerability
> [+] KB with the most recent release date
> - ID: KB5005030
> - Release date: 20210812
> 
> with windows 10 x64 1809 and hotfix i have 202 vulnerabilities
> without hotfix i have 203 vulnerabilites
> 
> on website : https://msrc.microsoft.com/update-guide/ with filters products familly windows and product windows 10 1809 x64 i have more 1500 vulnerabilties
> 
> i don't understand why wesng bypass lot of vulnerabilities (exemple : CVE-2021-34460, CVE-2021-34527, CVE-2021-34456, CVE-2021-33774, CVE-2020-17096 etc etc.) because no kb was install.
> 
> how to explain ?
> 
> best regards
> 
> @bitsadmin

The reason that false positive missing KBs show up is because of Microsoft's incomplete KB supersedence information. For more info check the "Eliminating false positives" link on **step 4** of the **Usage** heading: https://github.com/bitsadmin/wesng#usage.

Regarding the MSRC update guide website you refer to, you are only able to filter based on the major Windows 10 release, while you cannot specify any KBs you have already installed. A clean install of Windows 10 build 1809 without any updates would indeed be vulnerable to many CVEs. However, your system has probably been installing its updates and therefore is most likely protected against all public exploits.

I am currently in the process of finalizing a blog on how Windows versions/updates work, and how WES-NG can help to identify missing KBs, including ways to eliminate false positives. Keep an eye on my blog (https://bitsadm.in/) or Twitter (https://twitter.com/bitsadmin) where I will publish/announce it!
