### ISSUE TITLE
When I run wesng I get missing updates when I run windows update no missing updates at all

### ISSUE THREAD

**Issue by AwesomeAL** [bitsadmin/wesng#74]
![image](https://user-images.githubusercontent.com/42872637/235488204-bee93945-8ca9-447b-94a3-921f7ab2d439.png)

![image](https://user-images.githubusercontent.com/42872637/235488266-4f043001-960f-4022-9827-6362f4b87e17.png)

when using [https://learn.microsoft.com/en-us/windows/win32/wua_sdk/using-wua-to-scan-for-updates-offline](https://learn.microsoft.com/en-us/windows/win32/wua_sdk/using-wua-to-scan-for-updates-offline) also 

![image](https://user-images.githubusercontent.com/42872637/235488533-467eb641-1609-4543-8866-3a493ec58ff1.png)

**Comment by bitsadmin** [comment]
This happens because unfortunately the supersedence information in the dataset provided by Microsoft is not complete. For more information about this, check out the Eliminating False Positives section in the following blog post: https://blog.bitsadmin.com/blog/windows-security-updates-for-hackers#eliminating-false-positives
